extract = {
    'purch_machinery_equip': 'No',
        'optional_worktags': '',
        'driver_grant': '',
        'toggle_cost_center': '',
        'purch_total_amount_hide': '500.00',
        'purch_multiple_funding_srcs': 'No',
        'purch_receiver_contact': 'Caitlin DeShazo-Couchot',
        'driver_container_start': '',
        'IO:780312dbc34b3150926e19a4e40131b6': 'true',
        'se_routing_shared_environment': 'College of Engineering Shared Environment',
        'purch_calculate_total_confirm': 'true',
        'fin_uw_netid': 'mamishev',
        'purch_employee_status': 'student',
        'se_routing_uwm': 'false',
        'se_routing_related_cc': 'CC103212',
        'purch_total_amount': '500.00',
        'toggle_default_cost_center': '',
        'se_routing_position_str': 'PN-0000620 PROFESSOR, Electrical Engineering - Mamishev, Alexander V',
        'purch_ship_to_address3': '',
        'purch_assoc_dept': 'Electrical and Computer Engineering',
        'purch_ship_to_address2': '',
        'purch_ship_to_address1': '2610 164TH ST SW A406',
        'purch_qualify': '',
        'se_routing_se_override_list': '',
        'optional_assignee': '',
        'fdm_budget_company': 'b7722c2687f7e994b302ca64dabb3549',
        'more_information': 'true',
        'se_routing_related_bu': 'BU132 College of Engineering',
        'purch_ship_to_state': 'Washington',
        'driver_program': '',
        'fin_purch_line_items_mrvs': '[{"purch_line_total_cost":"500.00","purch_line_supplier":"","purch_line_uom":"","purch_item_url":"","purch_line_qty":"1","purch_line_unit_cost":"","purch_line_description":"Awarded for research within UW IAC","purch_line_item":"Sustainable Communities Award"}]',
        'purch_provide_detail': '',
        'fdm_budget': 'true',
        'optional_adhoc_program': '',
        'purch_home_address': 'Yes',
        'se_routing_positions_list': '',
        'purch_ship_to_country': 'USA',
        'fin_purchase_request_summary': 'true',
        'driver_gift': '',
        'fin_request_for': 'someone_else',
        'IO:f40312dbc34b3150926e19a4e40131ab': 'false',
        'billing_info': '',
        'toggle_resource': '',
        'optional_container_start2': '',
        'worktag_type': '',
        'optional_container_start4': '',
        'fin_purchase_request_base': 'true',
        'driver_project': '',
        'optional_container_start3': '',
        'optional_activity': '',
        'purch_email': 'mamishev@uw.edu',
        'purch_ship_to_zip': '98087',
        'driver_resource': '',
        'fin_shared_requester_info': 'true',
        'more_information_label': '',
        'purch_ship_to_city': 'Lynnwood',
        'driver_cost_center': '',
        'overwrite_worktags': '',
        'fin_requester_info_label': '',
        'purch_approver': 'mamishev',
        'toggle_container_start2': '',
        'optional_container_start': '',
        'purch_ship_to_address': '',
        'additional_comments': 'If needed, use discretionary budget GF120957',
        'fin_contact_number': '+1 206 221-5729',
        'purch_uw_purpose': 'Student Research Award',
        'toggle_container_start': '',
        'fin_shared_shared_environment_routing': 'true',
        'optional_other_worktags': '',
        'purch_detail_label': '',
        'optional_adhoc_standalone_grant': '',
        'purch_purchase_info_label': '',
        'toggle_default_resource': '',
        'driver_activity': '',
}

print(",".join(extract.keys()))